// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/compiler/options.proto

package com.randioo.protocGenAscript;

public final class Options {
  private Options() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.randioo.protocGenAscript.Options.as3Bindable);
    registry.add(com.randioo.protocGenAscript.Options.as3AmfAlias);
    registry.add(com.randioo.protocGenAscript.Options.as3AmfAutoAlias);
    registry.add(com.randioo.protocGenAscript.Options.as3ClientSideService);
    registry.add(com.randioo.protocGenAscript.Options.as3ServerSideService);
  }
  public static final int AS3_BINDABLE_FIELD_NUMBER = 9393;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> as3Bindable = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int AS3_AMF_ALIAS_FIELD_NUMBER = 9394;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> as3AmfAlias = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int AS3_AMF_AUTO_ALIAS_FIELD_NUMBER = 9395;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> as3AmfAutoAlias = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int AS3_CLIENT_SIDE_SERVICE_FIELD_NUMBER = 9396;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.Boolean> as3ClientSideService = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int AS3_SERVER_SIDE_SERVICE_FIELD_NUMBER = 9397;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.Boolean> as3ServerSideService = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&google/protobuf/compiler/options.proto" +
      "\032 google/protobuf/descriptor.proto:=\n\014as" +
      "3_bindable\022\037.google.protobuf.MessageOpti" +
      "ons\030\261I \001(\010:\005false:7\n\ras3_amf_alias\022\037.goo" +
      "gle.protobuf.MessageOptions\030\262I \001(\t:C\n\022as" +
      "3_amf_auto_alias\022\037.google.protobuf.Messa" +
      "geOptions\030\263I \001(\010:\005false:G\n\027as3_client_si" +
      "de_service\022\037.google.protobuf.ServiceOpti" +
      "ons\030\264I \001(\010:\004true:H\n\027as3_server_side_serv" +
      "ice\022\037.google.protobuf.ServiceOptions\030\265I ",
      "\001(\010:\005falseB\036\n\034com.randioo.protocGenAscri" +
      "pt"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          as3Bindable.internalInit(descriptor.getExtensions().get(0));
          as3AmfAlias.internalInit(descriptor.getExtensions().get(1));
          as3AmfAutoAlias.internalInit(descriptor.getExtensions().get(2));
          as3ClientSideService.internalInit(descriptor.getExtensions().get(3));
          as3ServerSideService.internalInit(descriptor.getExtensions().get(4));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
